### ISSUE TITLE
Add support for Hexo 5

### ISSUE THREAD

**Issue by tomap** [ertrzyiks/hexo-test-utils#30]
Hello, could you add support for hexo 5?

Thank you ;)

(and maybe anticipate hexo 6?)

**Comment by ertrzyiks** [comment]
Hey @tomap, I will add it to my TODO list for this week, thanks for the suggestion!

**Comment by ertrzyiks** [comment]
Hexo 5 should be supported by `hexo-test-utils@0.5.0`

**Comment by ertrzyiks** [comment]
W can't have hexo 6 in the testing pipeline before it's shipped, so I leave a PR for that to merge once hexo 6 is out.
https://github.com/ertrzyiks/hexo-test-utils/pull/33
